#!/usr/bin/env bash
set -euo pipefail

# In-container entrypoint for the sysbox sandbox (Phase B.1: sidecar proxy).
#
# Runs as root (container UID 0, which sysbox remaps to an unprivileged host
# subuid). Startup sequence:
#
#   1. Wait for sidecar proxy CA (shared via Docker volume)
#   2. Install the CA into the system trust store + Java keystore
#   3. Add default route via sidecar (agent's only path to the internet)
#   4. Start the inner Docker daemon (picks up CA from system store)
#   5. Drop to the unprivileged `claude` user and launch the agent
#
# The egress proxy runs in a SEPARATE sidecar container. This entrypoint does
# NOT start the proxy or configure iptables — those are handled by the sidecar.
# This is the Phase B.1 security improvement: even if the agent gains root and
# manipulates iptables inside this container, it has no effect because the
# enforcement is external (in the sidecar's network namespace).

CA_SHARE_DIR="/shared-ca"
SIDECAR_IP="${SANDBOX_SIDECAR_IP:-}"
FIREWALL_DISABLED="${SANDBOX_DISABLE_FIREWALL:-}"

# ---------- 1. wait for sidecar CA ----------

if [[ "$FIREWALL_DISABLED" == "1" ]]; then
    echo "WARN: sidecar proxy routing disabled (SANDBOX_DISABLE_FIREWALL=1)." >&2
else
    if [[ -z "$SIDECAR_IP" ]]; then
        echo "ERROR: SANDBOX_SIDECAR_IP not set (required for sidecar proxy routing)." >&2
        exit 1
    fi

    echo "Waiting for sidecar proxy CA..."
    for _ in $(seq 1 60); do
        [[ -f "$CA_SHARE_DIR/.sidecar-ready" ]] && break
        sleep 0.5
    done

    if [[ ! -f "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" ]]; then
        echo "ERROR: sidecar CA not found at $CA_SHARE_DIR/mitmproxy-ca-cert.pem" >&2
        echo "       Is the sidecar container running?" >&2
        exit 1
    fi

    # ---------- 2. install CA ----------

    echo "Installing sidecar proxy CA into system trust store..."
    cp "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" /usr/local/share/ca-certificates/mitmproxy-ca.crt
    update-ca-certificates 2>/dev/null

    # Export env vars that various runtimes need to trust the CA.
    cat > /etc/profile.d/proxy-ca.sh <<CAEOF
# Per-run proxy CA — auto-generated by sidecar, not a persistent secret.
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export NODE_EXTRA_CA_CERTS=$CA_SHARE_DIR/mitmproxy-ca-cert.pem
CAEOF

    # Java trust store (for Maven, Flyway, etc.)
    JAVA_HOME_DIR="$(dirname "$(dirname "$(readlink -f "$(which java)")")")" || true
    if [[ -n "$JAVA_HOME_DIR" && -f "$JAVA_HOME_DIR/lib/security/cacerts" ]]; then
        keytool -importcert -noprompt -trustcacerts \
            -alias mitmproxy-sandbox \
            -file "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" \
            -keystore "$JAVA_HOME_DIR/lib/security/cacerts" \
            -storepass changeit 2>/dev/null || true
        echo "Proxy CA installed into Java trust store."
    fi

    echo "Proxy CA installed into system trust store."

    # ---------- 3. set default route via sidecar ----------
    # The agent container is on an internal Docker network with no internet
    # gateway. The sidecar is our only path out. Docker's --internal flag
    # prevents the bridge from forwarding to the host, so even if the agent
    # manipulates its own routing table, the only reachable next hop on the
    # internal network is the sidecar.

    # Replace the default route (Docker's bridge gateway) with the sidecar.
    # The agent's traffic must go through the sidecar for L7 policy enforcement.
    echo "Setting default route via sidecar ($SIDECAR_IP)..."
    ip route replace default via "$SIDECAR_IP" || {
        echo "WARN: could not set default route via sidecar." >&2
    }
fi

# ---------- 4. start inner dockerd ----------

echo "Starting inner Docker daemon (nested, via sysbox)..."

# /var/lib/docker is a per-instance volume mounted by the launcher so parallel
# agents never share a data-root.
dockerd >/var/log/dockerd.log 2>&1 &
DOCKERD_PID=$!

# Wait for the daemon socket to come up.
for _ in $(seq 1 30); do
    if docker info >/dev/null 2>&1; then
        echo "Inner dockerd ready."
        break
    fi
    if ! kill -0 "$DOCKERD_PID" 2>/dev/null; then
        echo "ERROR: inner dockerd exited during startup. Log tail:" >&2
        tail -n 40 /var/log/dockerd.log >&2 || true
        exit 1
    fi
    sleep 1
done

if ! docker info >/dev/null 2>&1; then
    echo "ERROR: inner dockerd did not become ready within 30s. Log tail:" >&2
    tail -n 40 /var/log/dockerd.log >&2 || true
    exit 1
fi

# ---------- 5. drop privileges and launch the agent ----------
# See run-claude-docker.sh for the full explanation of why `bash -c` can't
# support Ctrl-Z and the rcfile/PROMPT_COMMAND trick is needed.

AGENT_CMD="${SANDBOX_AGENT_CMD:?SANDBOX_AGENT_CMD not set by the launcher}"

shift  # consume the "--" separator
for arg in "$@"; do
    AGENT_CMD+=" $(printf '%q' "$arg")"
done

AGENT_RCFILE="/tmp/agent-bashrc"
cat > "$AGENT_RCFILE" <<RCEOF
[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc
[ -f ~/.bashrc ] && . ~/.bashrc
[ -f /etc/profile.d/proxy-ca.sh ] && . /etc/profile.d/proxy-ca.sh

_launch_agent() {
    unset PROMPT_COMMAND
    $AGENT_CMD
    local rc=\$?
    if jobs -s | grep -q .; then
        echo "(agent suspended — type 'fg' to resume, 'exit' to quit)"
        return
    fi
    exit "\$rc"
}
PROMPT_COMMAND=_launch_agent
RCEOF
chown claude:claude "$AGENT_RCFILE"

export PATH=$PATH:/home/claude/.local/bin

# Source the proxy CA env vars so the agent's tools trust the MITM cert.
[[ -f /etc/profile.d/proxy-ca.sh ]] && . /etc/profile.d/proxy-ca.sh

exec runuser -u claude -- bash --rcfile "$AGENT_RCFILE" -i
