#!/usr/bin/env bash
set -euo pipefail

# In-container entrypoint for the sysbox sandbox (Phase B.1: sidecar proxy).
#
# Runs as root (container UID 0, which sysbox remaps to an unprivileged host
# subuid). Startup sequence:
#
#   1. Wait for sidecar proxy CA (shared via Docker volume)
#   2. Install the CA into the system trust store + Java keystore
#   3. Configure proxy env vars (HTTP_PROXY / HTTPS_PROXY)
#   4. Start the inner Docker daemon (with proxy config so pulls work)
#   5. Drop to the unprivileged `claude` user and launch the agent
#
# The egress proxy runs in a SEPARATE sidecar container on an --internal Docker
# network. Docker's --internal flag enforces mandatory network isolation at the
# host level — even if the agent gains root and ignores the proxy env vars,
# packets to external IPs are DROPped by host iptables. No iptables, routes,
# or NET_ADMIN needed inside this container.

CA_SHARE_DIR="/shared-ca"
PROXY_URL="${SANDBOX_PROXY_URL:-}"
FIREWALL_DISABLED="${SANDBOX_DISABLE_FIREWALL:-}"

# ---------- 1. wait for sidecar CA ----------

if [[ "$FIREWALL_DISABLED" == "1" ]]; then
    echo "WARN: sidecar proxy disabled (SANDBOX_DISABLE_FIREWALL=1)." >&2
else
    if [[ -z "$PROXY_URL" ]]; then
        echo "ERROR: SANDBOX_PROXY_URL not set (required for sidecar proxy)." >&2
        exit 1
    fi

    echo "Waiting for sidecar proxy CA..."
    for _ in $(seq 1 60); do
        [[ -f "$CA_SHARE_DIR/.sidecar-ready" ]] && break
        sleep 0.5
    done

    if [[ ! -f "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" ]]; then
        echo "ERROR: sidecar CA not found at $CA_SHARE_DIR/mitmproxy-ca-cert.pem" >&2
        echo "       Is the sidecar container running?" >&2
        exit 1
    fi

    # ---------- 2. install CA ----------

    echo "Installing sidecar proxy CA into system trust store..."
    cp "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" /usr/local/share/ca-certificates/mitmproxy-ca.crt
    update-ca-certificates 2>/dev/null

    # ---------- 3. proxy + CA env vars ----------
    # These are sourced by the agent's shell (via profile.d) and exported for
    # all child processes. no_proxy exempts local/private traffic so the inner
    # dockerd socket and localhost services (DB containers etc.) work directly.

    NO_PROXY="localhost,127.0.0.1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"

    cat > /etc/profile.d/proxy-ca.sh <<CAEOF
# Per-run proxy + CA config — auto-generated by entrypoint.
export HTTP_PROXY=$PROXY_URL
export HTTPS_PROXY=$PROXY_URL
export http_proxy=$PROXY_URL
export https_proxy=$PROXY_URL
export NO_PROXY=$NO_PROXY
export no_proxy=$NO_PROXY
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export NODE_EXTRA_CA_CERTS=$CA_SHARE_DIR/mitmproxy-ca-cert.pem
CAEOF

    # Java trust store (for Maven, Flyway, etc.)
    JAVA_HOME_DIR="$(dirname "$(dirname "$(readlink -f "$(which java)")")")" || true
    if [[ -n "$JAVA_HOME_DIR" && -f "$JAVA_HOME_DIR/lib/security/cacerts" ]]; then
        keytool -importcert -noprompt -trustcacerts \
            -alias mitmproxy-sandbox \
            -file "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" \
            -keystore "$JAVA_HOME_DIR/lib/security/cacerts" \
            -storepass changeit 2>/dev/null || true
        echo "Proxy CA installed into Java trust store."
    fi

    # ---------- configure apt proxy ----------
    # sudo resets env (env_reset in sudoers), so apt-get doesn't see
    # HTTP_PROXY/HTTPS_PROXY. Drop a persistent apt config file.
    cat > /etc/apt/apt.conf.d/99sandbox-proxy <<APTEOF
Acquire::http::Proxy "$PROXY_URL";
Acquire::https::Proxy "$PROXY_URL";
APTEOF

    echo "Proxy configured: $PROXY_URL"

    # ---------- configure inner dockerd proxy ----------
    # The inner dockerd needs proxy config so registry pulls (docker pull)
    # route through the sidecar. Docker reads proxy settings from
    # /etc/systemd/system/docker.service.d/ (systemd) or ~/.docker/config.json
    # (client). For the daemon itself, we use the daemon environment.
    mkdir -p /etc/systemd/system/docker.service.d
    cat > /etc/systemd/system/docker.service.d/proxy.conf <<DCONF
[Service]
Environment="HTTP_PROXY=$PROXY_URL"
Environment="HTTPS_PROXY=$PROXY_URL"
Environment="NO_PROXY=$NO_PROXY"
DCONF

    # Also export for the current process so dockerd inherits them.
    export HTTP_PROXY="$PROXY_URL"
    export HTTPS_PROXY="$PROXY_URL"
    export NO_PROXY="$NO_PROXY"
fi

# ---------- 4. ensure sandbox helper directory ----------
# Phase C: the credential helper and git config overlay are bind-mounted into
# /opt/sandbox/ by the launcher. Ensure the directory exists and is readable.
mkdir -p /opt/sandbox
chmod 755 /opt/sandbox

# ---------- 5. start inner dockerd ----------

echo "Starting inner Docker daemon (nested, via sysbox)..."

# /var/lib/docker is a per-instance volume mounted by the launcher so parallel
# agents never share a data-root.
dockerd >/var/log/dockerd.log 2>&1 &
DOCKERD_PID=$!

# Wait for the daemon socket to come up.
for _ in $(seq 1 30); do
    if docker info >/dev/null 2>&1; then
        echo "Inner dockerd ready."
        break
    fi
    if ! kill -0 "$DOCKERD_PID" 2>/dev/null; then
        echo "ERROR: inner dockerd exited during startup. Log tail:" >&2
        tail -n 40 /var/log/dockerd.log >&2 || true
        exit 1
    fi
    sleep 1
done

if ! docker info >/dev/null 2>&1; then
    echo "ERROR: inner dockerd did not become ready within 30s. Log tail:" >&2
    tail -n 40 /var/log/dockerd.log >&2 || true
    exit 1
fi

# ---------- 6. drop privileges and launch the agent ----------
# See run-claude-docker.sh for the full explanation of why `bash -c` can't
# support Ctrl-Z and the rcfile/PROMPT_COMMAND trick is needed.

AGENT_CMD="${SANDBOX_AGENT_CMD:?SANDBOX_AGENT_CMD not set by the launcher}"

shift  # consume the "--" separator
for arg in "$@"; do
    AGENT_CMD+=" $(printf '%q' "$arg")"
done

AGENT_RCFILE="/tmp/agent-bashrc"
cat > "$AGENT_RCFILE" <<RCEOF
[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc
[ -f ~/.bashrc ] && . ~/.bashrc
[ -f /etc/profile.d/proxy-ca.sh ] && . /etc/profile.d/proxy-ca.sh

_launch_agent() {
    unset PROMPT_COMMAND
    $AGENT_CMD
    local rc=\$?
    if jobs -s | grep -q .; then
        echo "(agent suspended — type 'fg' to resume, 'exit' to quit)"
        return
    fi
    exit "\$rc"
}
PROMPT_COMMAND=_launch_agent
RCEOF
chown claude:claude "$AGENT_RCFILE"

export PATH=$PATH:/home/claude/.local/bin

# Source the proxy CA env vars so the agent's tools trust the MITM cert.
[[ -f /etc/profile.d/proxy-ca.sh ]] && . /etc/profile.d/proxy-ca.sh

exec runuser -u claude -- bash --rcfile "$AGENT_RCFILE" -i
