#!/usr/bin/env bash
set -euo pipefail

# In-container entrypoint for the sysbox sandbox.
#
# Runs as root (container UID 0, which sysbox remaps to an unprivileged host
# subuid). Startup sequence:
#
#   1. Wait for sidecar proxy CA (shared via Docker volume)
#   2. Install the CA into the system trust store + Java keystore
#   3. Configure proxy env vars (HTTP_PROXY / HTTPS_PROXY)
#   4. Start the inner Docker daemon (with proxy config so pulls work)
#   5. Drop to the unprivileged `claude` user and launch the agent
#
# The egress proxy runs in a SEPARATE sidecar container on an --internal Docker
# network. Docker's --internal flag enforces mandatory network isolation at the
# host level — even if the agent gains root and ignores the proxy env vars,
# packets to external IPs are DROPped by host iptables. No iptables, routes,
# or NET_ADMIN needed inside this container.

CA_SHARE_DIR="/shared-ca"
PROXY_URL="${SANDBOX_PROXY_URL:-}"

# ---------- 1. wait for sidecar CA ----------

if [[ -z "$PROXY_URL" ]]; then
    echo "ERROR: SANDBOX_PROXY_URL not set (required for sidecar proxy)." >&2
    exit 1
fi

echo "Waiting for sidecar proxy CA..."
for _ in $(seq 1 60); do
    [[ -f "$CA_SHARE_DIR/.sidecar-ready" ]] && break
    sleep 0.5
done

if [[ ! -f "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" ]]; then
    echo "ERROR: sidecar CA not found at $CA_SHARE_DIR/mitmproxy-ca-cert.pem" >&2
    echo "       Is the sidecar container running?" >&2
    exit 1
fi

# ---------- 2. install CA ----------

echo "Installing sidecar proxy CA into system trust store..."
cp "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" /usr/local/share/ca-certificates/mitmproxy-ca.crt
update-ca-certificates 2>/dev/null

# ---------- 3. proxy + CA env vars ----------
# These are sourced by the agent's shell (via profile.d) and exported for
# all child processes. no_proxy exempts local/private traffic so the inner
# dockerd socket and localhost services (DB containers etc.) work directly.

NO_PROXY="localhost,127.0.0.1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"

# The JVM can't parse CIDR in nonProxyHosts — it wants `|`-separated glob
# patterns, so the private ranges are widened to prefix wildcards.
JAVA_NON_PROXY="localhost|127.*|[::1]|10.*|192.168.*"
for _o in 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31; do
    JAVA_NON_PROXY+="|172.$_o.*"
done

PROXY_HOSTPORT="${PROXY_URL#*://}"
PROXY_HOST="${PROXY_HOSTPORT%%:*}"
PROXY_PORT="${PROXY_HOSTPORT##*:}"

# Java ignores HTTP_PROXY/HTTPS_PROXY; it only reads these system
# properties. JAVA_TOOL_OPTIONS applies them to every JVM the agent starts
# (mvn, flyway, gradle daemon, ad-hoc `java -jar`) without wrapping each.
JAVA_PROXY_OPTS="-Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT"
JAVA_PROXY_OPTS+=" -Dhttps.proxyHost=$PROXY_HOST -Dhttps.proxyPort=$PROXY_PORT"
JAVA_PROXY_OPTS+=" -Dhttp.nonProxyHosts=$JAVA_NON_PROXY"

cat > /etc/profile.d/proxy-ca.sh <<CAEOF
# Per-run proxy + CA config — auto-generated by entrypoint.
export HTTP_PROXY=$PROXY_URL
export HTTPS_PROXY=$PROXY_URL
export http_proxy=$PROXY_URL
export https_proxy=$PROXY_URL
export NO_PROXY=$NO_PROXY
export no_proxy=$NO_PROXY
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export NODE_EXTRA_CA_CERTS=$CA_SHARE_DIR/mitmproxy-ca-cert.pem
export JAVA_TOOL_OPTIONS="$JAVA_PROXY_OPTS"
CAEOF

# Java trust store (for Maven, Flyway, etc.)
JAVA_HOME_DIR="$(dirname "$(dirname "$(readlink -f "$(which java)")")")" || true
if [[ -n "$JAVA_HOME_DIR" && -f "$JAVA_HOME_DIR/lib/security/cacerts" ]]; then
    keytool -importcert -noprompt -trustcacerts \
        -alias mitmproxy-sandbox \
        -file "$CA_SHARE_DIR/mitmproxy-ca-cert.pem" \
        -keystore "$JAVA_HOME_DIR/lib/security/cacerts" \
        -storepass changeit 2>/dev/null || true
    echo "Proxy CA installed into Java trust store."
fi

# ---------- Maven proxy settings ----------
# Maven's resolver uses Apache HttpClient, which does NOT read the JVM's
# http.proxyHost system properties — settings.xml is the only thing it
# honours. Written as global settings so a user-level ~/.m2/settings.xml
# (if the launcher ever mounts one) still layers on top. The stock Debian
# file is examples-only comments, so it's overwritten outright.
cat > /etc/maven/settings.xml <<MVNEOF
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
  <proxies>
    <proxy>
      <id>sandbox-http</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>$PROXY_HOST</host>
      <port>$PROXY_PORT</port>
      <nonProxyHosts>$JAVA_NON_PROXY</nonProxyHosts>
    </proxy>
    <proxy>
      <id>sandbox-https</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>$PROXY_HOST</host>
      <port>$PROXY_PORT</port>
      <nonProxyHosts>$JAVA_NON_PROXY</nonProxyHosts>
    </proxy>
  </proxies>
</settings>
MVNEOF
echo "Maven proxy settings written to /etc/maven/settings.xml."

# ---------- configure apt proxy ----------
# Persistent apt config so apt works even from contexts where the profile.d
# env hasn't been sourced (non-login shells, scripts).
cat > /etc/apt/apt.conf.d/99sandbox-proxy <<APTEOF
Acquire::http::Proxy "$PROXY_URL";
Acquire::https::Proxy "$PROXY_URL";
APTEOF

echo "Proxy configured: $PROXY_URL"

# ---------- configure inner dockerd proxy ----------
# The inner dockerd needs proxy config so registry pulls (docker pull)
# route through the sidecar. Docker reads proxy settings from
# /etc/systemd/system/docker.service.d/ (systemd) or ~/.docker/config.json
# (client). For the daemon itself, we use the daemon environment.
mkdir -p /etc/systemd/system/docker.service.d
cat > /etc/systemd/system/docker.service.d/proxy.conf <<DCONF
[Service]
Environment="HTTP_PROXY=$PROXY_URL"
Environment="HTTPS_PROXY=$PROXY_URL"
Environment="NO_PROXY=$NO_PROXY"
DCONF

# Also export for the current process so dockerd inherits them.
export HTTP_PROXY="$PROXY_URL"
export HTTPS_PROXY="$PROXY_URL"
export NO_PROXY="$NO_PROXY"

# ---------- 4. ensure sandbox helper directory ----------
# The credential helper and git config overlay are bind-mounted into
# /opt/sandbox/ by the launcher. Ensure the directory exists and is readable.
mkdir -p /opt/sandbox
chmod 755 /opt/sandbox

# ---------- 5. start inner dockerd ----------

echo "Starting inner Docker daemon (nested, via sysbox)..."

# /var/lib/docker is a per-instance volume mounted by the launcher so parallel
# agents never share a data-root.
dockerd >/var/log/dockerd.log 2>&1 &
DOCKERD_PID=$!

# Wait for the daemon socket to come up.
for _ in $(seq 1 30); do
    if docker info >/dev/null 2>&1; then
        echo "Inner dockerd ready."
        break
    fi
    if ! kill -0 "$DOCKERD_PID" 2>/dev/null; then
        echo "ERROR: inner dockerd exited during startup. Log tail:" >&2
        tail -n 40 /var/log/dockerd.log >&2 || true
        exit 1
    fi
    sleep 1
done

if ! docker info >/dev/null 2>&1; then
    echo "ERROR: inner dockerd did not become ready within 30s. Log tail:" >&2
    tail -n 40 /var/log/dockerd.log >&2 || true
    exit 1
fi

# ---------- 6. drop privileges and launch the agent ----------
# We need a real interactive bash with an active prompt loop so that Ctrl-Z
# suspends the agent and drops to a shell (fg to resume).
#
# Why `bash -c` doesn't work (even with -i or set -m): it executes the command
# string and exits — there is no read-eval-print loop. When the child is
# stopped by SIGTSTP, bash has no prompt to return to, so it just exits, taking
# the container with it.
#
# Instead: start a real interactive bash via --rcfile, whose PROMPT_COMMAND
# launches the agent exactly once at the first prompt — by which point job
# control is active. Ctrl-Z then works normally.

AGENT_CMD="${SANDBOX_AGENT_CMD:?SANDBOX_AGENT_CMD not set by the launcher}"

shift  # consume the "--" separator
for arg in "$@"; do
    AGENT_CMD+=" $(printf '%q' "$arg")"
done

AGENT_RCFILE="/tmp/agent-bashrc"
cat > "$AGENT_RCFILE" <<RCEOF
[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc
[ -f ~/.bashrc ] && . ~/.bashrc
[ -f /etc/profile.d/proxy-ca.sh ] && . /etc/profile.d/proxy-ca.sh

_launch_agent() {
    unset PROMPT_COMMAND
    $AGENT_CMD
    local rc=\$?
    if jobs -s | grep -q .; then
        echo "(agent suspended — type 'fg' to resume, 'exit' to quit)"
        return
    fi
    exit "\$rc"
}
PROMPT_COMMAND=_launch_agent
RCEOF
chown claude:claude "$AGENT_RCFILE"

export PATH=$PATH:/home/claude/.local/bin

# Source the proxy CA env vars so the agent's tools trust the MITM cert.
[[ -f /etc/profile.d/proxy-ca.sh ]] && . /etc/profile.d/proxy-ca.sh

exec runuser -u claude -- bash --rcfile "$AGENT_RCFILE" -i
